# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
pip install torch torchvision torchaudio

   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
    --------------------------------------- 2.1/114.6 MB 12.7 MB/s eta 0:00:09
   - -------------------------------------- 3.9/114.6 MB 9.9 MB/s eta 0:00:12
   -- ------------------------------------- 6.3/114.6 MB 10.3 MB/s eta 0:00:11
   -- ------------------------------------- 8.4/114.6 MB 10.9 MB/s eta 0:00:10
   --- ------------------------------------ 9.7/114.6 MB 9.4 MB/s eta 0:00:12
   ---- ----------------------------------- 12.8/114.6 MB 10.5 MB/s eta 0:00:10
   ----- ---------------------------------- 16.5/114.6 MB 11.3 MB/s eta 0:00:09
   ----- ---------------------------------- 16.8/114.6 MB 11.4 MB/s eta 0:00:09
   ----- ---------------------------------- 17.0/114.6 MB 9.0 MB/s eta 0:00:11
   ------- -------------------------------- 21.0/114.6 MB 9.9 MB/s eta 0:00:10
   -------- ------------------------------- 23.9/114.6 MB 10.3 MB/s eta 0:00:09
   --------- ------------------------------ 27.5/114.6 MB 


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)

print(random_tensor)
print(random_tensor.shape)

tensor([[0.3737, 0.3749, 0.2892, 0.0265, 0.0238, 0.8178, 0.8230],
        [0.2996, 0.0705, 0.7687, 0.5940, 0.8820, 0.7322, 0.5464],
        [0.2578, 0.9399, 0.5165, 0.0299, 0.3998, 0.6768, 0.1439],
        [0.4183, 0.7616, 0.9683, 0.6189, 0.2917, 0.2246, 0.5666],
        [0.7569, 0.6204, 0.8699, 0.6537, 0.6430, 0.4076, 0.4622],
        [0.7123, 0.6447, 0.2744, 0.7103, 0.9431, 0.1615, 0.2395],
        [0.8067, 0.7247, 0.0975, 0.8982, 0.8973, 0.1890, 0.1783]])
torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
random_tensor_2 = torch.rand(1, 7)

# Perform matrix multiplication
result = torch.matmul(random_tensor, random_tensor_2.T)

# Optional: Print the result and its shape
print(result)
print(result.shape)


tensor([[1.8707],
        [2.4680],
        [1.6077],
        [2.4869],
        [2.8367],
        [2.1406],
        [2.0853]])
torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)

# Matrix multiply tensors
result = torch.matmul(tensor_A, tensor_B.T)

# Print the result and its shape as a tuple to match the requested output
print((result, result.shape))

(tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]), torch.Size([7, 1]))


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
GPU_SEED = 1234
torch.cuda.manual_seed(GPU_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

# Print the tensors as a tuple to match the expected output
print((tensor_A, tensor_B))

Device: cpu
(tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]), tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]]))



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [9]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(tensor_A, tensor_B.T)

# Print the result and its shape to match the expected output
print((result, result.shape))

(tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]), torch.Size([2, 2]))


### 8. Find the maximum and minimum values of the output of 7.

In [10]:
# Find max
max_value = torch.max(result)

# Find min
min_value = torch.min(result)

# Print the results
print(f"Maximum value: {max_value}")
print(f"Minimum value: {min_value}")

Maximum value: 0.5617256760597229
Minimum value: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [11]:
# Find arg max
arg_max = torch.argmax(result)

# Find arg min
arg_min = torch.argmin(result)

# Print the results
print(f"Index of maximum value: {arg_max}")
print(f"Index of minimum value: {arg_min}")

Index of maximum value: 3
Index of minimum value: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [12]:
# Set seed
torch.manual_seed(7)

# Create random tensor
original_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
squeezed_tensor = original_tensor.squeeze()


# Print out tensors and their shapes
print(original_tensor, original_tensor.shape)
print(squeezed_tensor, squeezed_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
