<a href="https://colab.research.google.com/github/gravity102424/ESAA/blob/main/ESAA_YB_WEEK1_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print("NumPy version:",np.__version__)
np.show_config()

NumPy version: 2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: 

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null = np.zeros(10)
print(null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
array = np.array([1,2,3,4,5])
print(array.nbytes)

40


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
num = np.zeros(10)
num[4] = 1
print(num)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
num = np.arange(10,50)
print(num)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
num_rev = np.sort(num)[::-1]
print(num_rev)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
matrix = np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
A = np.array([1,2,0,0,4,0])
A_non_zero = (A!=0)
indices  = np.arange(len(A))[A_non_zero]
print(indices)

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
identity = np.zeros(9)
identity = identity.reshape(3,3)
for i in [0,1,2]:
  identity[i,i] = 1
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
random_array = np.random.random((3,3,3))
print(random_array)

[[[0.20252757 0.20351044 0.44075265]
  [0.39284598 0.64011492 0.92974619]
  [0.17643855 0.10745835 0.08279793]]

 [[0.64464351 0.36588469 0.47268519]
  [0.36836181 0.2855778  0.77945753]
  [0.80062514 0.44218527 0.02969735]]

 [[0.36027888 0.01942522 0.49169693]
  [0.92031215 0.1274414  0.49259217]
  [0.41268621 0.54529032 0.09587269]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
random_array = np.random.random((10,10))
print(random_array)
print(random_array.min())
print(random_array.max())

[[0.40000438 0.80924173 0.24144582 0.21462625 0.86361814 0.39594941
  0.61613819 0.36683865 0.51695057 0.95533256]
 [0.26864242 0.43344317 0.99698373 0.58401799 0.61819663 0.85822119
  0.41742971 0.95057125 0.38688285 0.34980014]
 [0.7519029  0.31595195 0.4775443  0.4598201  0.70863528 0.32965687
  0.4694153  0.4589576  0.80129859 0.41324343]
 [0.20115824 0.33106725 0.29150663 0.80560056 0.93514612 0.20585339
  0.80195345 0.86947223 0.24725135 0.36840087]
 [0.37124304 0.08255218 0.71838652 0.12314964 0.83529046 0.58551274
  0.92093419 0.39893846 0.67798665 0.62076315]
 [0.601929   0.95152137 0.23651706 0.08320933 0.95589992 0.36107313
  0.47390953 0.90977179 0.75209721 0.8778361 ]
 [0.13814798 0.54302077 0.23996494 0.15337387 0.63293573 0.38266189
  0.35764132 0.03443156 0.68779756 0.93551719]
 [0.959858   0.83670254 0.35568463 0.15417701 0.99574002 0.93886086
  0.60076394 0.00362824 0.56061699 0.95775282]
 [0.05602568 0.79714035 0.32162158 0.75739927 0.18004942 0.71280857
  0.93486942

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
random_vector = np.random.random(30)
print(random_vector)
print(random_vector.mean())

[0.19797524 0.75913293 0.61221178 0.99668688 0.1861211  0.50324754
 0.99967605 0.85319713 0.17871462 0.54935004 0.10416688 0.58634031
 0.47657545 0.82896733 0.2849961  0.8248566  0.48247615 0.61049282
 0.39396826 0.32999811 0.71090374 0.4854785  0.59301785 0.00387831
 0.38214337 0.46171133 0.48682703 0.15472761 0.07510578 0.30415953]
0.4805701458271456


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array2d = np.ones((5,5))
array2d[1:-1,1:-1]=0
print(array2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True



```
# 코드로 형식 지정됨
```

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
mat_5 = np.zeros((5,5))
for i in [0,1,2,3]:
  mat_5[i+1,i] = i+1
print(mat_5)



[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
mat_8 = np.zeros((8,8))
for i in range(8):
  for j in range(8):
    if (i+j)%2 == 0:
      mat_8[i,j] = 1

print(mat_8)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
np.unravel_index(100,(6,7,8))

(np.int64(1), np.int64(5), np.int64(4))

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
mat_5 = np.random.random((5,5))
mean = mat_5.mean()
std = mat_5.std()
mat_5 = (mat_5-mean)/std
print(mat_5)

[[-0.27439764 -1.86043313  0.88575729  1.02169688 -0.49696679]
 [ 0.80143069  0.83521864  0.43213754 -1.0117423   0.64636321]
 [-1.69041518 -1.79582098 -0.85412513 -1.34151559 -0.70109222]
 [ 0.65812998  0.60621645  0.56388007 -1.27549474  0.77070633]
 [ 1.03839181  1.05111326  0.58344915  0.22243975  1.18507262]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
rgba_dtype = np.dtype([
    ('r', np.ubyte),   # red
    ('g', np.ubyte),   # green
    ('b', np.ubyte),   # blue
    ('a', np.ubyte),   # alpha
])
print(rgba_dtype)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
